Fix : NPE in SapphireToolTip
org.eclipse.swt.SWTException: Failed to execute runnable java.lang.NullPointerException) 
	at org.eclipse.swt.SWT.error(SWT.java:4397) 
	at org.eclipse.swt.SWT.error(SWT.java:4312) 
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:138) 
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4145) 
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3762) 
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:826) 
	at org.eclipse.jface.window.Window.open(Window.java:802) 
	at org.eclipse.ui.internal.navigator.wizards.WizardShortcutAction.run(WizardShortcutAction.java:98) 
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:499) 
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584) 
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501) 
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:411) 
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84) 
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057) 
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4170) 
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759) 
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113) 
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332) 
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997) 
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138) 
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610) 
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332) 
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567) 
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150) 
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124) 
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196) 
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110) 
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79) 
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354) 
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181) 
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
	at java.lang.reflect.Method.invoke(Method.java:606) 
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636) 
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591) 
	at org.eclipse.equinox.launcher.Main.run(Main.java:1450) 
	at org.eclipse.equinox.launcher.Main.main(Main.java:1426) 
Caused by: java.lang.NullPointerException 
	at org.eclipse.sapphire.ui.forms.swt.internal.SapphireToolTip$2$1.run(SapphireToolTip.java:130) 
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35) 
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135) 
	... 35 more 

Bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=424152