Fix : Property is disposed exception caused by FunctionResult.equal()
java.lang.IllegalStateException: Id property is already disposed.
	at org.eclipse.sapphire.Property.assertNotDisposed(Property.java:761)
	at org.eclipse.sapphire.Property.init(Property.java:83)
	at org.eclipse.sapphire.Value.text(Value.java:244)
	at org.eclipse.sapphire.Value.text(Value.java:239)
	at org.eclipse.sapphire.modeling.el.FunctionResult.equal(FunctionResult.java:684)
	at org.eclipse.sapphire.modeling.el.FunctionResult.refresh(FunctionResult.java:287)
	at org.eclipse.sapphire.modeling.el.FunctionResult.refresh(FunctionResult.java:251)
	at org.eclipse.sapphire.modeling.el.ModelElementFunctionContext$ReadPropertyFunction$1$1.handle(ModelElementFunctionContext.java:253)
	at org.eclipse.sapphire.ListenerContext$BroadcastJob.run(ListenerContext.java:193)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:131)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:138)
	at org.eclipse.sapphire.ui.SapphirePart.broadcast(SapphirePart.java:560)
	at org.eclipse.sapphire.ui.SapphirePart.initialize(SapphirePart.java:210)
	at org.eclipse.sapphire.ui.forms.PageBookPart.changePage(PageBookPart.java:201)
	at org.eclipse.sapphire.ui.forms.WithPart.updateCurrentPage(WithPart.java:179)
	at org.eclipse.sapphire.ui.forms.WithPart.access$2(WithPart.java:172)
	at org.eclipse.sapphire.ui.forms.WithPart$1.handleTypedEvent(WithPart.java:74)
	at org.eclipse.sapphire.ui.forms.WithPart$1.handleTypedEvent(WithPart.java:1)
	at org.eclipse.sapphire.FilteredListener.handle(FilteredListener.java:35)
	at org.eclipse.sapphire.ListenerContext$BroadcastJob.run(ListenerContext.java:193)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:131)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:138)
	at org.eclipse.sapphire.ui.SapphirePart.broadcast(SapphirePart.java:560)
	at org.eclipse.sapphire.ui.SapphirePart.initialize(SapphirePart.java:210)
	at org.eclipse.sapphire.ui.forms.PageBookPart.changePage(PageBookPart.java:201)
	at org.eclipse.sapphire.ui.forms.WithPart.updateCurrentPage(WithPart.java:179)
	at org.eclipse.sapphire.ui.forms.WithPart.access$2(WithPart.java:172)
	at org.eclipse.sapphire.ui.forms.WithPart$1.handleTypedEvent(WithPart.java:74)
	at org.eclipse.sapphire.ui.forms.WithPart$1.handleTypedEvent(WithPart.java:1)
	at org.eclipse.sapphire.FilteredListener.handle(FilteredListener.java:35)
	at org.eclipse.sapphire.ListenerContext$BroadcastJob.run(ListenerContext.java:193)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:131)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:138)
	at org.eclipse.sapphire.Property.broadcast(Property.java:709)
	at org.eclipse.sapphire.ElementHandle.refreshContent(ElementHandle.java:138)
	at org.eclipse.sapphire.ElementHandle.refresh(ElementHandle.java:63)
	at org.eclipse.sapphire.ElementHandle.content(ElementHandle.java:315)
	at org.eclipse.sapphire.ui.forms.swt.internal.WithPresentation$1$6.widgetSelected(WithPresentation.java:340)
	at org.eclipse.sapphire.ui.forms.swt.RadioButtonsGroup.handleWidgetSelectedEvent(RadioButtonsGroup.java:221)
	at org.eclipse.sapphire.ui.forms.swt.RadioButtonsGroup.access$0(RadioButtonsGroup.java:209)
	at org.eclipse.sapphire.ui.forms.swt.RadioButtonsGroup$1.widgetSelected(RadioButtonsGroup.java:96)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4170)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1426)

Bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=423823