Fix : CheckBoxListPropertyEditorRenderer accesses a disposed element
When CheckBoxListPropertyEditorRenderer is used and parent element is
deleted, an exception is thrown because the renderer is attempting to
access an element that has already been disposed.

To reproduce the problem using web.xml editor, follow these steps:

1. Under Security/Constraints, create a new security constraint.
2. Create a new web resource collection for the constraint.
3. In the web resource collection, check a few HTTP method types.
4. Delete the security constraint.

java.lang.IllegalStateException: WebResourceCollection element is already disposed.
	at org.eclipse.sapphire.modeling.ModelElement.assertNotDisposed(ModelElement.java:1671)
	at org.eclipse.sapphire.modeling.ModelElement.read(ModelElement.java:211)
	at org.eclipse.sapphire.ui.renderers.swt.ListPropertyEditorRenderer.getList(ListPropertyEditorRenderer.java:84)
	at org.eclipse.sapphire.ui.renderers.swt.CheckBoxListPropertyEditorRenderer$2.getElements(CheckBoxListPropertyEditorRenderer.java:205)
	at org.eclipse.jface.viewers.StructuredViewer.getRawChildren(StructuredViewer.java:1010)
	at org.eclipse.jface.viewers.ColumnViewer.getRawChildren(ColumnViewer.java:703)
	at org.eclipse.jface.viewers.AbstractTableViewer.getRawChildren(AbstractTableViewer.java:1087)
	at org.eclipse.jface.viewers.StructuredViewer.getFilteredChildren(StructuredViewer.java:917)
	at org.eclipse.jface.viewers.StructuredViewer.getSortedChildren(StructuredViewer.java:1067)
	at org.eclipse.jface.viewers.AbstractTableViewer.internalRefreshAll(AbstractTableViewer.java:701)
	at org.eclipse.jface.viewers.AbstractTableViewer.internalRefresh(AbstractTableViewer.java:649)
	at org.eclipse.jface.viewers.AbstractTableViewer.internalRefresh(AbstractTableViewer.java:636)
	at org.eclipse.jface.viewers.StructuredViewer$7.run(StructuredViewer.java:1508)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1443)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1404)
	at org.eclipse.jface.viewers.CheckboxTableViewer.preservingSelection(CheckboxTableViewer.java:326)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1506)
	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:537)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1465)
	at org.eclipse.sapphire.ui.renderers.swt.CheckBoxListPropertyEditorRenderer.refresh(CheckBoxListPropertyEditorRenderer.java:500)
	at org.eclipse.sapphire.ui.renderers.swt.CheckBoxListPropertyEditorRenderer.handleListElementChangedEvent(CheckBoxListPropertyEditorRenderer.java:436)
	at org.eclipse.sapphire.ui.renderers.swt.ListPropertyEditorRenderer$1.handle(ListPropertyEditorRenderer.java:43)
	at org.eclipse.sapphire.ListenerContext$BroadcastJob.run(ListenerContext.java:182)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:120)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:127)
	at org.eclipse.sapphire.modeling.ModelElement.broadcast(ModelElement.java:1584)
	at org.eclipse.sapphire.modeling.ModelElement.dispose(ModelElement.java:1622)
	at org.eclipse.sapphire.modeling.ModelElement.dispose(ModelElement.java:1649)
	at org.eclipse.sapphire.modeling.ModelElementList.refresh(ModelElementList.java:202)
	at org.eclipse.sapphire.modeling.ModelElementList.refresh(ModelElementList.java:112)
	at org.eclipse.sapphire.modeling.ModelElementList.remove(ModelElementList.java:456)
	at org.eclipse.sapphire.ui.form.editors.masterdetails.internal.OutlineNodeDeleteActionHandler.run(OutlineNodeDeleteActionHandler.java:79)
	at org.eclipse.sapphire.ui.SapphireActionHandler.execute(SapphireActionHandler.java:94)
	at org.eclipse.sapphire.ui.swt.renderer.SapphireMenuActionPresentation$2.widgetSelected(SapphireMenuActionPresentation.java:126)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4169)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3758)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)

https://bugs.eclipse.org/bugs/show_bug.cgi?id=394819