Fix : ClassCastException in SapphireHotSpotsActionPresentation
An exception is thrown when an action handler factory is added to the
Sapphire.EditorPage context.

java.lang.ClassCastException: org.eclipse.sapphire.ui.forms.swt.MasterDetailsEditorPage$1 cannot be cast to org.eclipse.sapphire.ui.forms.swt.presentation.FormComponentPresentation
	at org.eclipse.sapphire.ui.forms.swt.presentation.internal.SapphireHotSpotsActionPresentation.displayActionHandlerChoice(SapphireHotSpotsActionPresentation.java:73)
	at org.eclipse.sapphire.ui.forms.swt.presentation.internal.SapphireToolBarActionPresentation$1.widgetSelected(SapphireToolBarActionPresentation.java:119)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4170)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)

Bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=419551
Signed-off-by: Gregory Amerson <gregory.amerson@liferay.com>