Fix : Widget is disposed exception when using table property editor
Exceptions like this one are seen when the table is disposed in the
middle of an operation. This can happen if a list selection page book
is present and it doesn't specify the default page. The lack of the
default page causes the page book to change visibility when selection
changes between empty and non-empty. The change of page book visibility
triggers a re-render from the nearest composite part, which often will
include the table.

org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4397)
	at org.eclipse.swt.SWT.error(SWT.java:4312)
	at org.eclipse.swt.SWT.error(SWT.java:4283)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:472)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:344)
	at org.eclipse.swt.widgets.Table.setRedraw(Table.java:4765)
	at org.eclipse.jface.viewers.ColumnViewer.editElement(ColumnViewer.java:451)
	at org.eclipse.sapphire.ui.renderers.swt.DefaultListPropertyEditorRenderer$16.handle(DefaultListPropertyEditorRenderer.java:711)
	at org.eclipse.sapphire.ListenerContext$BroadcastJob.run(ListenerContext.java:182)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:120)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:127)
	at org.eclipse.sapphire.ui.SapphireActionSystemPart.broadcast(SapphireActionSystemPart.java:350)
	at org.eclipse.sapphire.ui.SapphireActionHandler.execute(SapphireActionHandler.java:110)
	at org.eclipse.sapphire.ui.swt.renderer.SapphireToolBarActionPresentation$1.widgetSelected(SapphireToolBarActionPresentation.java:124)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4170)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1426)

Bugzilla : https://bugs.eclipse.org/bugs/show_bug.cgi?id=415185