Enhancement : EL Absolute function for paths
AbsolutePathFunctionTests can fail in some environments due to canonical
path differences.

junit.framework.AssertionFailedError: expected:<d:/Eclipse/Sapphire/0.7.x/abc/file.txt> but was:<D:/Eclipse/Sapphire/0.7.x/abc/file.txt>
	at org.eclipse.sapphire.tests.modeling.el.functions.absolute.AbsolutePathFunctionTests.testAbsolutePathFunction(AbsolutePathFunctionTests.java:62)
	at org.eclipse.test.EclipseTestRunner.run(EclipseTestRunner.java:655)
	at org.eclipse.test.EclipseTestRunner.run(EclipseTestRunner.java:310)
	at org.eclipse.test.UITestApplication$2.run(UITestApplication.java:197)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4145)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3762)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:613)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.test.UITestApplication.runApplication(UITestApplication.java:140)
	at org.eclipse.test.UITestApplication.run(UITestApplication.java:62)
	at org.eclipse.test.UITestApplication.start(UITestApplication.java:212)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:80)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:372)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:226)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1426)
	at org.eclipse.core.launcher.Main.main(Main.java:34)

Tests : AbsolutePathFunctionTests
Bugzilla : https://bugs.eclipse.org/bugs/show_bug.cgi?id=414821