Fix : IllegalArgumentException caused by ModelBasedPossibleValuesService
To reproduce, drag-n-drop contacts in the contacts repository sample
editor.

java.lang.IllegalArgumentException: Path "Contacts/Name" is invalid for org.eclipse.sapphire.samples.contacts.Contact.
	at org.eclipse.sapphire.ElementImpl.createIllegalPathException(ElementImpl.java:1012)
	at org.eclipse.sapphire.ElementImpl.attach(ElementImpl.java:840)
	at org.eclipse.sapphire.ElementImpl.attach(ElementImpl.java:782)
	at org.eclipse.sapphire.services.internal.ModelBasedPossibleValuesService.init(ModelBasedPossibleValuesService.java:80)
	at org.eclipse.sapphire.services.Service.initIfNecessary(Service.java:56)
	at org.eclipse.sapphire.services.ServiceContext.services(ServiceContext.java:179)
	at org.eclipse.sapphire.Property.services(Property.java:478)
	at org.eclipse.sapphire.Property.service(Property.java:447)
	at org.eclipse.sapphire.services.internal.PossibleValuesValidationService$Condition.applicable(PossibleValuesValidationService.java:100)
	at org.eclipse.sapphire.services.ServiceProxy.service(ServiceProxy.java:97)
	at org.eclipse.sapphire.services.ServiceContext.services(ServiceContext.java:133)
	at org.eclipse.sapphire.Property.services(Property.java:478)
	at org.eclipse.sapphire.Property.refreshValidation(Property.java:246)
	at org.eclipse.sapphire.Value.refresh(Value.java:70)
	at org.eclipse.sapphire.ElementImpl.refresh(ElementImpl.java:595)
	at org.eclipse.sapphire.ElementHandle.refresh(ElementHandle.java:68)
	at org.eclipse.sapphire.ElementHandle.content(ElementHandle.java:288)
	at org.eclipse.sapphire.ui.swt.ModelElementsTransfer.nativeToJava(ModelElementsTransfer.java:208)
	at org.eclipse.sapphire.ui.swt.ModelElementsTransfer.nativeToJava(ModelElementsTransfer.java:174)
	at org.eclipse.swt.dnd.DropTarget.Drop(DropTarget.java:443)
	at org.eclipse.swt.dnd.DropTarget.Drop_64(DropTarget.java:392)
	at org.eclipse.swt.dnd.DropTarget$3.method6(DropTarget.java:260)
	at org.eclipse.swt.internal.ole.win32.COMObject.callback6(COMObject.java:119)
	at org.eclipse.swt.internal.ole.win32.COM.DoDragDrop(Native Method)
	at org.eclipse.swt.dnd.DragSource.drag(DragSource.java:363)
	at org.eclipse.swt.dnd.DragSource.access$0(DragSource.java:289)
	at org.eclipse.swt.dnd.DragSource$1.handleEvent(DragSource.java:172)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1058)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4170)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:613)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:80)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:372)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:226)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1426)

Bugzilla : https://bugs.eclipse.org/bugs/show_bug.cgi?id=416074