Fix : ClassCastException when the delete key is used in the outline
An exception is thrown when the delete key is used to delete nodes in
the master-details editor page.

java.lang.ClassCastException: org.eclipse.sapphire.ui.forms.swt.MasterDetailsEditorPage$1 cannot be cast to org.eclipse.sapphire.ui.forms.swt.FormComponentPresentation
	at org.eclipse.sapphire.ui.forms.swt.SapphireKeyboardActionPresentation.handleKeyEvent(SapphireKeyboardActionPresentation.java:184)
	at org.eclipse.sapphire.ui.forms.swt.SapphireKeyboardActionPresentation.handleKeyEvent(SapphireKeyboardActionPresentation.java:110)
	at org.eclipse.sapphire.ui.forms.swt.SapphireKeyboardActionPresentation.access$0(SapphireKeyboardActionPresentation.java:106)
	at org.eclipse.sapphire.ui.forms.swt.SapphireKeyboardActionPresentation$2.handleEvent(SapphireKeyboardActionPresentation.java:81)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1081)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1108)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1104)
	at org.eclipse.swt.widgets.Widget.wmKeyDown(Widget.java:1827)
	at org.eclipse.swt.widgets.Control.WM_KEYDOWN(Control.java:4975)
	at org.eclipse.swt.widgets.Tree.WM_KEYDOWN(Tree.java:6137)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4643)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:6005)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4977)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2549)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3757)
	at org.eclipse.sapphire.ui.forms.swt.Popup.open(Popup.java:250)
	at org.eclipse.sapphire.ui.forms.swt.internal.SapphireToolTip.toolTipShow(SapphireToolTip.java:406)
	at org.eclipse.sapphire.ui.forms.swt.internal.SapphireToolTip.toolTipOpen(SapphireToolTip.java:509)
	at org.eclipse.sapphire.ui.forms.swt.internal.SapphireToolTip.toolTipCreate(SapphireToolTip.java:371)
	at org.eclipse.sapphire.ui.forms.swt.internal.SapphireToolTip.access$2(SapphireToolTip.java:347)
	at org.eclipse.sapphire.ui.forms.swt.internal.SapphireToolTip$ToolTipOwnerControlListener.handleEvent(SapphireToolTip.java:645)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4170)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1426)

Bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=422616