Releng : Export documentation as part of the build
Removed export-documentation from the hudson-build target as Sapphire
Hudson instance is still hitting permission errors.

java.io.IOException: Cannot run program "/jobs/genie.technology.sapphire/8.0.x/workspace/build/documentation/eclipse/eclipse" (in directory "/jobs/genie.technology.sapphire/8.0.x/workspace/build/documentation/eclipse"): java.io.IOException: error=13, Permission denied
 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:470)
	at java.lang.Runtime.exec(Runtime.java:593)
	at org.eclipse.help.internal.standalone.Eclipse.run(Eclipse.java:92)
Caused by: java.io.IOException: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:148)
	at java.lang.ProcessImpl.start(ProcessImpl.java:65)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:452)
	... 2 more