Fix : RuntimeException when selecting from multi-select list in sample
Added missing @GenerateImpl annotation.

java.lang.RuntimeException: MultiSelectEnumItem : Could not instantiate implementation class.
	at org.eclipse.sapphire.modeling.ModelElementType.instantiate(ModelElementType.java:324)
	at org.eclipse.sapphire.modeling.ModelElementList.refresh(ModelElementList.java:169)
	at org.eclipse.sapphire.modeling.ModelElementList.refresh(ModelElementList.java:112)
	at org.eclipse.sapphire.modeling.ModelElement.refresh(ModelElement.java:706)
	at org.eclipse.sapphire.modeling.ModelElement.refresh(ModelElement.java:572)
	at org.eclipse.sapphire.modeling.ModelElement.refresh(ModelElement.java:526)
	at org.eclipse.sapphire.ui.swt.xml.editor.XmlEditorResourceStore$RefreshElementTask.run(XmlEditorResourceStore.java:478)

Bugzilla : https://bugs.eclipse.org/bugs/show_bug.cgi?id=408293