Fix : IllegalArgumentException when label includes "<" character
If sdef label text includes "<" character either directly or indirectly
via an expression, an IllegalArgumentException like the following is
thrown during rendering. The "<" character needs to be escaped 
as "&lt;".

java.lang.IllegalArgumentException: Argument not valid The element type "init" must be terminated by the matching end-tag "</init>".
	at org.eclipse.swt.SWT.error(SWT.java:4263)
	at org.eclipse.sapphire.ui.swt.renderer.internal.formtext.FormTextModel.parseInputStream(FormTextModel.java:148)
	at org.eclipse.sapphire.ui.swt.renderer.internal.formtext.FormTextModel.parseTaggedText(FormTextModel.java:126)
	at org.eclipse.sapphire.ui.swt.renderer.internal.formtext.SapphireFormText.setText(SapphireFormText.java:690)
	at org.eclipse.sapphire.ui.LabelPart.refreshLabel(LabelPart.java:160)
	at org.eclipse.sapphire.ui.LabelPart.render(LabelPart.java:100)
	at org.eclipse.sapphire.ui.SapphirePartContainer.render(SapphirePartContainer.java:86)
	at org.eclipse.sapphire.ui.PageBookPart$1.handle(PageBookPart.java:99)
	at org.eclipse.sapphire.ListenerContext$BroadcastJob.run(ListenerContext.java:171)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:109)
	at org.eclipse.sapphire.ui.SapphirePart.broadcast(SapphirePart.java:332)
	at org.eclipse.sapphire.ui.PageBookPart.changePage(PageBookPart.java:180)
	at org.eclipse.sapphire.ui.PageBookPart.changePage(PageBookPart.java:148)
	at org.eclipse.sapphire.ui.SapphireListControlledPageBook$1$1.run(SapphireListControlledPageBook.java:141)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:180)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:150)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4683)
	at org.eclipse.sapphire.ui.SapphireListControlledPageBook$1.handle(SapphireListControlledPageBook.java:145)
	at org.eclipse.sapphire.ListenerContext$BroadcastJob.run(ListenerContext.java:171)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:109)
	at org.eclipse.sapphire.services.Service.broadcast(Service.java:92)
	at org.eclipse.sapphire.ui.ListSelectionService.select(ListSelectionService.java:84)
	at org.eclipse.sapphire.ui.renderers.swt.DefaultListPropertyEditorRenderer$4.selectionChanged(DefaultListPropertyEditorRenderer.java:314)
	at org.eclipse.sapphire.ui.renderers.swt.DefaultListPropertyEditorRenderer$SelectionProvider.notifySelectionChangedListeners(DefaultListPropertyEditorRenderer.java:2188)
	at org.eclipse.sapphire.ui.renderers.swt.DefaultListPropertyEditorRenderer$SelectionProvider.access$0(DefaultListPropertyEditorRenderer.java:2182)
	at org.eclipse.sapphire.ui.renderers.swt.DefaultListPropertyEditorRenderer$SelectionProvider$1.selectionChanged(DefaultListPropertyEditorRenderer.java:2137)

https://bugs.eclipse.org/bugs/show_bug.cgi?id=389568